apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluegreen-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /bluegreen-demo
        pathType: Prefix
        backend:
          service:
            name: bluegreen-demo
            port:
              number: 80
      - path: /bluegreen-demo-preview
        pathType: Prefix
        backend:
          service:
            name: bluegreen-demo-preview
            port:
              number: 80