apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-demo
spec:
  project: default
  source:
    repoURL: https://github.com/YutaNonaka/argorollouts-sample.git
    targetRevision: main
    path: manifests/02_BlueGreen
  destination:
    server: https://kubernetes.default.svc
