apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-demo
spec:
  project: default
  source:
    repoURL: https://gitlab.com/h-meru/argorollouts-hands-on.git
    targetRevision: main
    path: manifests/03_Canary
  destination:
    server: https://kubernetes.default.svc