apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.6.4
resources:
- application-rollingupdate.yaml
- application-bluegreen.yaml
- application-canary.yaml
- application-progressive.yaml
- namespace.yaml
patchesStrategicMerge:
- secret.yaml