apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: progressive-analysis
spec:
  args:
  - name: target-endpoint
  - name: request-max-loop
  - name: sleep-duration
  - name: error-threshold
  metrics:
  - name: success-rate
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: analysis-job
                image: registry.gitlab.com/cloudnativetips/argorollouts-sample/analysis-job:latest
                imagePullPolicy: Always
                env:
                - name: TARGET_ENDPOINT
                  value: "{{args.target-endpoint}}"
                - name: REQUEST_MAX_LOOP
                  value: "{{args.request-max-loop}}"
                - name: SLEEP_DURATION
                  value: "{{args.sleep-duration}}"
                - name: ERROR_THRESHOLD
                  value: "{{args.error-threshold}}"
              restartPolicy: Never