apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: progressive-analysis
spec:
  args:
  - name: ingress-ip
  - name: target-endpoint
  - name: error-threshold
  metrics:
  - name: success-rate
    provider:
      job:
        spec:
          ttlSecondsAfterFinished: 60
          backoffLimit: 1
          template:
            spec:
              hostAliases:
              - ip: "{{ args.ingress-ip }}"
                hostnames:
                - "{{ args.target-endpoint }}"
              containers:
              - name: analysis-job
                image: registry.gitlab.com/cloudnativetips/argorollouts-sample/analysis-job:latest
                imagePullPolicy: Always
                env:
                - name: TARGET_ENDPOINT
                  value: "{{ args.target-endpoint }}"
                - name: ERROR_THRESHOLD
                  value: "{{ args.error-threshold }}"
              restartPolicy: Never