apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: progressive-analysis
spec:
  args:
  - name: target-endpoint
  - name: error-threshold
  metrics:
  - name: success-rate
    initialDelay: 5s
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: analysis-job
                image: registry.gitlab.com/cloudnativetips/argorollouts-sample/analysis-job:latest
                imagePullPolicy: Always
                env:
                - name: TARGET_ENDPOINT
                  value: "http://{{ args.target-endpoint }}/"
                - name: ERROR_THRESHOLD
                  value: "{{ args.error-threshold }}"
              restartPolicy: Never